### ISSUE TITLE
Citing cpp2 / cppfront

### ISSUE THREAD

**Issue by dutkalex** [hsutter/cppfront#1041]
Hi! I was wondering how can I cite your work on Cpp2 / Cppfront in research papers and technical reports. I could not find any reference article presenting this work...
Anyway, thanks for the amazing work!
Best regards,
Alex

**Comment by dutkalex** [comment]
```
cff-version: 1.2.0
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
title: cppfront
authors:
  - given-names: Herb
    family-names: Sutter
repository-code: 'https://github.com/hsutter/cppfront'
abstract: A personal experimental C++ Syntax 2 -> Syntax 1 compiler
license: CC-BY-NC-ND-4.0

```
